symbol_dictionary = {
    'Bear': 'Bears in our dreams usually symbolize our strength, power and independence. Knowing that bears are wild animals, they may be also a symbol of some untamed habits of a dreamer. Another meaning of a bear in yourdream may be a mother figure. ... You can dreamabout a peaceful bear or about a bear that is aggressive.',
    'Cliff': 'To see a cliff and also the sea can indicate that you will encounter troubled or difficult times ahead. Cliffs can also be associated with strength and vitality of life. To be walking beside a cliff side in a dream is associated with your inner and greater strength.',
    'Eagle': 'To dream of a flying eagle or one who is perched high signifies good fortune or victory coming your way. If it scares you or attacks you it means there are some self-imposed limitations you need to push through.',
    'Falling': 'Falling dreams also often reflect a sense of failure or inferiority in some circumstance or situation. ccording to Freudian theory, dreams of falling indicate that you are contemplating giving in to a sexual urge or impulse. You are lacking indiscretion.',
    'Flying': 'It is important to know what direction where you where going when you where flying high up in the clouds. Where you flying upwards, downwards or backwards? If you are flying upwards in your dream suggest you are now on a new level spiritually. If you where flying downwards we are trying to get more in tuned to our unconscious. If you are flying low to the ground it represents strength and determination in your life. If you are flying an airplane it means your not fully free to have fun but your almost there. If you are flying backwards suggests you want to relive the past and the good memories you experienced.',
    'Healing': 'The healing dreams can "tell" you that something is not quite right with your bodies even before any physical symptoms show up. Dreams of this nature may be telling the dreamer that he or she needs to go to the dentist or doctor.',
    'Hummingbird': 'If you dream that you are a hummingbird, this means that you have a great deal of freedom and a high level of self-actualization. Make sure that you turn that energy to good effect by keeping your mood high, and do not let yourself become worn out by trying to do too much too fast.',
    'Lions ': 'lions are considered the king of the jungle and represent authority over others. A lion could represent your desire to hold power over others, or it could indicate someone has control over you.',
    'Naked': 'indicates vulnerability, fear of exposure, insecurity, unpreparedness, or contrarily freedom of expression when unashamed.',
    'Pac Man': 'To see or play Pac Man in your dream represents some sort of habit or behavior that is taking over your daily life.',
    'Pregnancy': 'To dream that you are pregnant symbolizes an aspect of yourself or some aspect of your personal life that is growing and developing. You may not be ready to talk about it or act on it. Being pregnant in your dream may also represent the birth of a new idea, direction, project or goal. Alternatively, it may symbolize fear of new responsibilities.',
    'Rainbow': 'in dreams typically represent positive effects or perspectives since they usually occur after the rain. You need the right conditions and perspective to be able to see rainbows in real life, this translates to being at the right place and right time in your life when you encounter rainbows in dreams.',
    'Snake': 'wakeup call to face your fears OR growth an renewal with shedding of skin',
    'Spider': 'to dream of spidersmeans the dreamer is being manipulated by someone in waking life. Or the dreamer might be the one manipulating others in waking life. The explanation of such dream interpretation spiders has the ability to manipulate their prey into their web.',
    'Wave': 'In general, a rising tsunami or a tidal wave within a dream represents repressed feelings and emotions. Seeing or observing a tidal wave without being in the situation means that you are experiencing unhappiness and emotional instability in a waking life.',
    'Wedding': 'Wedding dreams can reflect our anxieties about recent life changes, our excitement about the future, or increased levels of self-acceptance',
    'Whale': 'whales usually represent a big event in your life or a strong feeling of solitude. ... The appearance of a whale in a dream can signify that everything is or will be o.k. and is often related to spiritual matters of the mind and heart.'
}
